name=ESP32-NimBLE-Keyboard_modified
version=0.4.1
author=T-vK
maintainer=tomorrow56
sentence=Bluetooth LE Keyboard library for the ESP32.
paragraph=Bluetooth LE Keyboard library for the ESP32.
category=Communication
url=https://github.com/tomorrow56/ESP32-NimBLE-Keyboard
architectures=esp32
